# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tarot-be-service
spec:
  type: LoadBalancer
  selector:
    app: tarot-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
